name: ci
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 https://github.com/actions/checkout/releases/tag/v4.1.1
      - name: install node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2 https://github.com/actions/setup-node/releases/tag/v3.8.2
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - run: npm test

  docker:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 https://github.com/actions/checkout/releases/tag/v4.1.1
      -
        name: install node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2 https://github.com/actions/setup-node/releases/tag/v3.8.2
        with:
          node-version: 20
      - run: npm install
      - run: npm test
      - run: rm -r node_modules && rm package-lock.json
      - run: npm install --omit=dev
      -
        name: Login to container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0 https://github.com/docker/login-action/releases/tag/v3.0.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        id: meta_seed
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0 https://github.com/docker/metadata-action/releases/tag/v5.5.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/hypercore-e2e-tests-seed
      -
        name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0 https://github.com/docker/build-push-action/releases/tag/v5.1.0
        with:
          context: .
          file: dockerfiles/seed
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta_seed.outputs.tags }}
          labels: ${{ steps.meta_seed.outputs.labels }}
      -
        id: meta_create
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0 https://github.com/docker/metadata-action/releases/tag/v5.5.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/hypercore-e2e-tests-create
      -
        name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0 https://github.com/docker/build-push-action/releases/tag/v5.1.0
        with:
          context: .
          file: dockerfiles/create
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta_create.outputs.tags }}
          labels: ${{ steps.meta_create.outputs.labels }}

  # daily_docker_build:
  #   if: ${{ github.event_name == 'schedule' || startsWith(github.ref, 'refs/tags/') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - # Needed for buildX, which accesses cwd
  #       name: Checkout
  #       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 https://github.com/actions/checkout/releases/tag/v4.1.1
  #     - run: npm install
  #     - run: npm test
  #     - run: rm -r node_modules && rm package-lock.json
  #     - run: npm install --omit=dev
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0 https://github.com/docker/setup-qemu-action/releases/tag/v3.0.0
  #     - # See note on build-push-action github repo on why this needed
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0 https://github.com/docker/setup-buildx-action/releases/tag/v3.0.0
  #     -
  #       name: Login to container registry
  #       uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0 https://github.com/docker/login-action/releases/tag/v3.0.0
  #       with:
  #         registry: "ghcr.io"
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     -
  #       name: Build and push Docker image
  #       uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0 https://github.com/docker/build-push-action/releases/tag/v5.1.0
  #       with:
  #         context: .
  #         platforms: linux/amd64
  #         push: true
  #         tags: ghcr.io/${{ github.repository_owner }}/hypercore-e2e-tests:build-with-latest-deps
  #         build-args: TAG=build-with-latest-deps
